library(pacman)
p_load(data.table,janitor,tidyr,stringr,rvest,purrr,glue,tictoc)
x1 <- fread("~/Downloads/BBMP_Voters_Download/urls_bbmp_220828.txt",header = F)
x1$V1 %>% uniqueN()
wards <- x1$V1 %>% str_extract("(?<=WARD).{1,8}|\\d+(?=-Ward)") %>% str_extract("\\d+")
ACs <- x1$V1 %>% str_extract("(?<=AC)\\d+") %>% sample(100)
fnames <- paste0("bbmp_voters.AC-",ACs,".Ward-",wards,".pdf")
indx <- sample(1:7717,size = 10)
tic("10files")
x1$V1[indx]  %>% walk2(fnames[indx],~download.file(.x,destfile = glue("~/R/voter_pdfs/{.y}")))
toc()